server:
  port: 7800
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  application:
    name: consumer-ribbon

#user:
#  userServicePath: http://localhost:7900/getUser/
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://kanyun:kanyun1234@localhost:8001/eureka
