server:
  port: 9001
  servlet:
    # 定义项目名[同时关联服务访问路径].此配置的含义为：hostname+port访问.不需要加项目名
    context-path: /


eureka:
  instance:
    environment: [test]
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
    hostname: localhost

  client:
    #是否将自己注册到Eureka Server， 默认为true。
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kanyun:kanyun1234@localhost:8001/eureka
    healthcheck:
      # 开启健康检查（依赖spring-boot-starter-actuator）
      enabled: true

spring:
  application:
    name: spring-cloud-config-client

