server:
  port: 9001
  servlet:
    # 定义项目名[同时关联服务访问路径].此配置的含义为：hostname+port访问.不需要加项目名
    context-path: /

spring:
  application:
    name: spring-cloud-config-client


# 利用spring-boot-starter-actuator实现配置半自动刷新【需要注意的是,这个是SpringCloudConfig的配置中心而非bus消息总线】
# 如果spring-cloud-config-client启动了多个实例[端口不一样],那么当配置改动并上传到github上时,需要发送多次
# webhook才能将所有实例的配置进行更新,而采用bus消息总线的话,只要这几个服务的实例在消息总线中,那么webhook只需要发送一次更新就可以了
# 消息总线会同步到其他实例中去
management:
  endpoints:
    web:
      exposure:
        include: refresh
